# Sources
source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.com:KZSLAB/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'hackaton-leboncoin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hackaton-leboncoin
  pod 'KZSLAB-AR-View'
  pod 'FanMenu'
  pod 'Moya', '~> 11.0'
end
